# Generated by Django 3.2.4 on 2021-06-20 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_user_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthday',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='modifed',
            new_name='modified',
        ),
    ]
